const OrderActionTypes = {
  TOGGLE_ORDERCART_HIDDEN: "TOGGLE_ORDERCART_HIDDEN",
  ADD_ORDERITEM: "ADD_ORDERITEM",
  REMOVE_ORDERITEM: "REMOVE_ORDERITEM",
  CLEAR_ORDERITEM_FROM_ORDERCART: "CLEAR_ORDERITEM_FROM_ORDERCART",
  CLEAR_ORDERCART: "CLEAR_ORDERCART",
  SET_ORDERCART_FROM_FIREBASE: "SET_ORDERCART_FROM_FIREBASE",
  UPDATE_ORDERCART_IN_FIREBASE: "UPDATE_ORDERCART_IN_FIREBASE",
};

export default OrderActionTypes;
