const WishActionTypes = {
  TOGGLE_WISHCART_HIDDEN: "TOGGLE_WISHCART_HIDDEN",
  ADD_WISHITEM: "ADD_WISHITEM",
  REMOVE_WISHITEM: "REMOVE_WISHITEM",
  CLEAR_WISHITEM_FROM_WISHCART: "CLEAR_WISHITEM_FROM_WISHCART",
  CLEAR_WISHCART: "CLEAR_WISHCART",
  SET_WISHCART_FROM_FIREBASE: "SET_WISHCART_FROM_FIREBASE",
  UPDATE_WISHCART_IN_FIREBASE: "UPDATE_WISHCART_IN_FIREBASE",
};

export default WishActionTypes;
